"""@skeleton docstring
The skeleton image contains only a few projects. More may be added
programatically in the future, but this file will guarantee that 
important projects and edge cases are explicitly included.

"""

projects = [
3060,       # drupal
# contributed modules
105916,     # coder
17345,      # pathauto
# themes
88566,      # zen
506436,     # omega
#distributions
837736,     # commons
1079066,    # commerce_kickstart
]

whitelist.add_project_multiple(projects)
